### ISSUE TITLE
The command "./config/travis/run-checks.sh && travis_retry ./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls asciidoctor copyDummySearchPage" exited with 1.

### ISSUE THREAD

**Issue by spencertan96** [nus-cs2103-AY1819S1/forum#47] opened 2018-09-26 08:59 UTC
Ran into another issue with TravisCI. 
![image](https://user-images.githubusercontent.com/42445828/46069129-6acb2000-c1ad-11e8-9a28-2b8c72577556.png)
Is it because I didn't set up coverage reporting with Coveralls??

**Comment by davidchoo12** [comment] 2018-09-28 17:29
You can try to split the travis script (line 6 of .travis.yml) to multiple lines to narrow down which one that fails
```
script:
  - ./config/travis/run-checks.sh
  - ./gradlew clean
  - ./gradlew checkstyleMain
  - ./gradlew checkstyleTest
  - ./gradlew headless
  - ./gradlew allTests
  - ./gradlew coverage
  - ./gradlew coveralls
  - ./gradlew asciidoctor
  - ./gradlew copyDummySearchPage
```

Then push your code to trigger build and travis will run each one sequentially, so it will take some time but you can narrow down the error this way.

**Comment by damithc** [comment] 2018-09-29 01:01
@spencertan96 it helps if you provide links to the failing PR

**Comment by spencertan96** [comment] 2018-09-30 14:55
Alright! I split up the travis script and got this:
![image](https://user-images.githubusercontent.com/42445828/46258884-c5dd7980-c503-11e8-8019-6c8493e14de4.png)
![image](https://user-images.githubusercontent.com/42445828/46258890-df7ec100-c503-11e8-8b29-d34994b0dfeb.png)
Only these 2 exit with 1.

**Comment by spencertan96** [comment] 2018-09-30 14:56
Link to the PR! https://travis-ci.org/CS2103-AY1819S1-W12-4/main

**Comment by damithc** [comment] 2018-10-01 12:06
The first screenshot has a description of the first problem. A code quality check is failing due to the stated problem. Try to fix that first.
The second problem may be caused by the change you did to travis.yml. After fixing the first problem, you can go back to the original travis.yml file to see if the second problem goes away too.

**Comment by spencertan96** [comment] 2018-10-02 10:59
Alright thank you! Fixed it!

**Comment by damithc** [comment] 2018-10-02 14:53
Good to hear that. Closing the issue.

**Closed as completed by damithc** 2018-10-02 14:53 UTC
