### ISSUE TITLE
Needing clarification for issues 142, 995 and 1239 of the PE results

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/forum#202] opened 2018-11-18 15:05 UTC
- Should [142](https://github.com/nus-cs2103-AY1819S1/pe-results/issues/142) be accepted and my teammate and I bear responsibility for it? (That's the current arrangement). It looks like this the image attached below. I also offered a detailed comment explaining why it happened. Well, _technically_ the commit was from my teammate (it was due to a whitespace character between "Format: `add event n/EVENT_NAME [s/START_DATETIME] [e/END_DATETIME] [d/DESCRIPTION] [v/VENUE] [rt/REPEAT_TYPE]
[ru/REPEAT_UNTIL_DATETIME] [t/TAG]... [re/REMINDER_TIME]…`" and the `) but the alias feature is under my minor feature also. Also, [a PE dry run issue from earlier](https://github.com/CS2103-AY1819S1-F11-1/main/issues/215) highlighted the same error and somehow we did not fix it ☹️ 
![image](https://user-images.githubusercontent.com/35895966/48675511-b50cc400-eb94-11e8-8727-7a98aece2dfe.png)

If we removed that whitespace character on line 74 of [our UG](https://github.com/CS2103-AY1819S1-F11-1/main/tree/master/docs/UserGuide.adoc)),
![image](https://user-images.githubusercontent.com/35895966/48675795-7547db80-eb98-11e8-9441-6f2d2a4c6876.png)

it would turn out like this (tried it out in "edit" mode of that doc on GitHub itself):
![image](https://user-images.githubusercontent.com/35895966/48675803-8d1f5f80-eb98-11e8-8a15-606229ae2cae.png)

- ~Can [995](https://github.com/nus-cs2103-AY1819S1/pe-results/issues/995) be rejected? It is a DG documentation inherited from AB-4 which we forgot to remove, but it is **under the Appendix named _Instructions for Manual Testing_**). Can it then be marked as a duplicate of [601](https://github.com/nus-cs2103-AY1819S1/pe-results/issues/601)? (Note: we also rejected 601 after I consulted Prof and he said it was okay to do so). 995's screenshot is shown below:~ **RESOLVED!!!**
![image](https://user-images.githubusercontent.com/35895966/48675624-3153d700-eb96-11e8-829d-b7f500ba0eba.png)~

- ~Can [1239](https://github.com/nus-cs2103-AY1819S1/pe-results/issues/1239) be accepted as duplicate of a typo/grammar bug? All typo/grammar bugs are currently marked as duplicates of [160](https://github.com/nus-cs2103-AY1819S1/pe-results/issues/160) for my team. Actually, can we reject 1239 or should we not do so?~ **RESOLVED!!**
![image](https://user-images.githubusercontent.com/35895966/48675638-46306a80-eb96-11e8-9314-324473957143.png)

Thank you!

**Comment by HEARTOFAL1ON** [comment] 2018-11-18 15:47
Hijacking this thread (it's my own thread though 😛) with another issue needing clarification hopefully:

Could [pe-results 995](https://github.com/nus-cs2103-AY1819S1/pe-results/issues/995) be marked as a duplicate of [pe-results 601](https://github.com/nus-cs2103-AY1819S1/pe-results/issues/601). Could 995 also then be rejected too as well?

995 is inherited content of DG which we forgot to remove:
![image](https://user-images.githubusercontent.com/35895966/48674863-12e8de00-eb8c-11e8-981e-d52686ebaaec.png). It is under [**Appendix H: Instructions for Manual Testing** of our DG](https://github.com/CS2103-AY1819S1-F11-1/main/tree/master/docs/DeveloperGuide.adoc#saving-data) though, which makes things a little confusing I guess? :/

601 is inherited content of UG which we forgot to remove:
![image](https://user-images.githubusercontent.com/35895966/48674870-30b64300-eb8c-11e8-95e1-a5db27bffeeb.png)

We have already gotten approval to reject 601 by Prof too.

**Comment by azhikai** [comment] 2018-11-18 16:01
If prof approves rejecting 601, then 995 can be rejected too (or marked as duplicate if it's all documentation related) since it's practically the same issue but in different documentation.

As a whole, I believe as long as it's inherited from AB4, you can reject it.

**Comment by HEARTOFAL1ON** [comment] 2018-11-18 16:10
Thanks @AZhiKai! I think it makes sense that

- 995 can be marked as a duplicate of 601 (reason: inherited from AB-4)
- Perhaps 995 can be rejected too

However, I don't wish to keep giving Prof more work as I have been bothering him quite a bit already 😅 , hence if what I said is correct, could Prof give this comment of mine a thumbs up? 😆 

Jk~ 😛

**Comment by ghost** [comment] 2018-11-18 17:01
Hi all, I have edited the original post of this thread since I wish to clarify a few issues together!

Thank you Zhi Kai once again for offering your opinion though! 😃 

P.S. Apologies for my long edited post, but I just wish to seek clarification!

**Closed as completed** 2018-11-19 08:45 UTC
